version: '3.3'
services:

    mysql:
        image: mysql:5.7
        deploy:
           mode: replicated
           replicas: 10
        networks:
          - dbnet
        hostname: mysql
        ports:
          - 3306:3306 
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: 'sysbench'
            MYSQL_BUFFERSIZE: '1G'
            MYSQL_LOGSIZE: '256M'
            MYSQL_FLUSHLOG: '1'
            MYSQL_FLUSHMETHOD: 'O_DIRECT'

    sysbench:
        depends_on:
          - mysql
        hostname: sysbench
        networks:
          - dbnet
        image: shaker242/sysbench:latest
        deploy:
            mode: replicated
            replicas: 10

networks:
   dbnet:
